### ISSUE TITLE
Can't install rabbitmq

### ISSUE THREAD

**Issue by neoformit** [usegalaxy-eu/ansible-rabbitmq#1]
I'm trying to install rabbitmq for pulsar setup following the [GTN tutorial](https://training.galaxyproject.org/training-material/topics/admin/tutorials/pulsar/tutorial.html). It fails with a dependency error. I tried pinning an `erlang` version as Simon suggests [here](https://lists.galaxyproject.org/archives/list/galaxy-dev@lists.galaxyproject.org/thread/3M2AS2O5NZB67452VQB24JQNAWH5MIBM/) but I keep getting the same error when I run the Ansible playbook:

```
MSG:

Dependency is not satisfiable: erlang-crypto (< 1:24.0)|esl-erlang (< 1:24.0)
```

I can install RabbitMQ fine on the debian CLI with the CloudSmith installation script provided by rabbitmq:
https://www.rabbitmq.com/install-debian.html#apt-quick-start-cloudsmith

The script does a lot of work adding PPAs which I assume provide the correct `erlang` (and associated package) versions. It also explicitly installs `erlang` dependencies.

I'm not sure what the proper fix for this issue is in the `usegalaxy_eu.rabbitmq` Ansible role but I wonder if the install should follow the procedure in the CloudSmith script?

Host machine is on Ubuntu 20.04 LTS.

**Comment by gmauro** [comment]
The GTN tutorial is using the `usegalaxy_eu.rabbitmq` role, but this repository is for the `usegalaxy_eu.rabbitmqserver`.
This role deploys a rabbitmq server using a Docker container just to avoid the problems you described and, the tutorial should be updated using the new role.

**Comment by hexylena** [comment]
It definitely should be updated! Would you be able to propose the changes @gmauro ? Even just the playbook diff would be helpful, and I can rewrite the text around it.

**Comment by neoformit** [comment]
Brilliant thanks @gmauro I'll try with `usegalaxy_eu.rabbitmqserver`.

**Comment by gmauro** [comment]
@hexylena I try to kick it during the weekend

**Comment by hexylena** [comment]
(apologies for writing outside of work hours) 

Just following up on this, @gmauro did you ever write that up, or @neoformit did you get it worked out? We'd love to update the training with that.

**Comment by neoformit** [comment]
Funny you mention, I'm sitting in the Pulsar tutorial with Simon now! I've updated my requirements to the `rabbitmqserver` role but haven't got the Pulsar working yet (for other reasons). Part of my issue is gradually building my playbook over a year and having out-of-date versions and variables. I'm not sure there's a simple way around that it's just the nature of the beast. I'll post an update if I have more issues with this.

**Comment by neoformit** [comment]
Just posted a [different issue](https://github.com/usegalaxy-eu/ansible-rabbitmq/issues/2)
